FROM node:18

WORKDIR /backend/
COPY ./package.json /backend/
COPY ./yarn.lock /backend/
COPY ./prisma/schema.prisma ./prisma/schema.prisma
RUN yarn install --production
RUN yarn prisma generate --production

COPY . /backend/
CMD yarn start:prod